### PR TITLE
Updated Selects link name from plural to singular and updated incorre…

### PR DESCRIPTION
**Pull request by KrisKnabel**
Updated Select Navigation Link name from Selects to Select.  Also updated incorrect reference from <input> to <select>.

### CODE REVIEW

**Comment by darintrimillos** [comment]
Do you want to also update the actual path to the Select docs?

**Comment by KrisKnabel** [comment]
> Do you want to also update the actual path to the Select docs?

No, just updating the display name from Selects to Select

**Comment by lancetharper** [comment]
Most of the links are plural. Did our copy editors ask for this?

**Comment by KrisKnabel** [comment]
> Most of the links are plural. Did our copy editors ask for this?

Yes :  https://rei.slack.com/archives/G3F7A6FR7/p1569859161009800

**Pull request merged**
